#!/usr/bin/perl

use FindBin;
use IO::Socket::INET;
use Data::Dumper;
use LWP::UserAgent;

push(@INC, $FindBin::Bin . "/../lib");

require S2Config;
require S2dbobj;

S2Config::setup('/home/sign-firmware/pi/conf/signd.xml');

$home = S2Config::getHomedir();
$logFile = S2Config::getConfigValue('logfile') || '/var/log/program.log';
unlink($logFile);

my $tty = `ls /dev/ttyUSB*`;

chop($tty);

slog("TTY: $tty");

if(! -c $tty) {
	slog("$tty doesn't exist. No sign plugged in?");
}

my $cmd = "/usr/local/bin/esptool.py --baud 921600 --port $tty write_flash 0x8000 /home/sign-firmware/util/part_table.bin 0x10000 /home/sign-firmware/NEIOSYS_HAILSIGN-ProdFirmware-SP/NEIOSYS_HAILSIGN-ProdFirmware-SP.ino.esp32.bin";

slog("Running $cmd");

open(PIPE,"$cmd|");

while($in = <PIPE>) {
	chop($in);
	slog($in);
}
close(PIPE);
slog(">>>DONE<<<");
slog("EOF");



sub slog {
	my $logFile = $main::logFile;
	my $msg = shift;

	open(LOG,">>$logFile");
	print LOG getTimestamp() . ": " . $msg . "\n";
	print getTimestamp() . ": " .  $msg . "\n" if($main::debug);
	close(LOG);
}

sub getTimestamp {
	my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time());
        return sprintf("%02d/%02d/%04d-%02d:%02d:%02d",$mon+1,$mday,$year+1900,$hour,$min,$sec);
}

