#!/usr/bin/perl


use Net::Bluetooth;
use Data::Dumper;
use IO::Handle;

my $device_ref = get_remote_devices();

print Dumper($device_ref);

my $obj = Net::Bluetooth->newsocket("RFCOMM");
$addr = 'C4:4F:33:58:B6:FB';

$port = 1;

if($obj->connect($addr, $port) != 0) {
     die "connect error: $!\n";
}

print Dumper($obj);

my $fh = $obj->perlfh();
$fh->autoflush(1);


print Dumper(FH);

sleep(1);

print "sending \n";

print $fh "V\n";
print "receiving\n";

$buf = readline($fh);
print "Fetchhost: $buf\n";



